environment = "staging"
environment_domain_prefix = "staging."
aws_account_id = ""
project_name = "my-cool-app"
aws_region = "us-west-2"
az_count = 2
app_port = 4000
app_count = 2
health_check_path = "/health"
fargate_cpu=256
fargate_memory=512
min_capacity=1
max_capacity=3
